apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hygieia-ui-deploy
  labels:
    app: hygieia-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hygieia-ui
  template:
    metadata:
      labels:
        app: hygieia-ui
    spec:
      containers:
      - name: hygieia-ui
        image: 537899582775.dkr.ecr.us-east-2.amazonaws.com/hygieia-api
        ports: 
        - containerPort: 3000
      imagePullSecrets:
        - name: regcred
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 8.8.8.8      